[Variables]
; Application 1
App1=NAME
App1Icon=#@#\Images\Icons\NAME.png
App1Path="PATH"
App1Parameters=""
App1Overlay="#@#\Images\Overlays\NAME.png"

; Application 2
App2=
App2Icon=
App2Path=
App2Parameters=
App2Overlay=

; Application 3
App3=
App3Icon=
App3Path=
App3Parameters=
App3Overlay=

; Application 4
App4=
App4Icon=
App4Path=
App4Parameters=
App4Overlay=

; Application 5
App5=
App5Icon=
App5Path=
App5Parameters=
App5Overlay=

; Application 6
App6=
App6Icon=
App6Path=
App6Parameters=
App6Overlay=

; Application 7
App7=
App7Icon=
App7Path=
App7Parameters=
App7Overlay=

; Application 8
App8=
App8Icon=
App8Path=
App8Parameters=
App8Overlay=
