[Variables]
; Color Values
white=255,255,255
coolWhite=253,253,253
grey=100,100,100
greyBlue=70,73,93
black=0,0,0
green=70,255,113
red=255,73,113
teal=90,222,205
orange=242,162,114
blurple=104,118,205
blue=121,230,243
lightBlue=33,147,176
skyBlue=109,213,237
purple=194,89,240
pink=243,127,151
googleBlue=5,80,245
googleRed=255,45,90

; Default Colors
background=40,42,54
lbackground=65,68,88
dbackground=29,31,40

; Font Options
BebasNeue=Bebas Neue
GoogleSans=Google Sans

; Color Scheme - Generic
font=#GoogleSans#
fontColor=#coolWhite#
fontHighlightColor=#teal#
shadowColor=#grey#
backgroundColor=#background#
darkBackgroundColor=#dbackground#
lightBackgroundColor=#lbackground#
containerBackgroundColor=#lbackground#
graphHorizontalLines=#greyBlue#

; Color Scheme - CPU
cpuFont=#font#
cpuFontColor=#fontColor#
cpuBackgroundColor=#lightBackgroundColor#
cpuGraphHorizontalLines=#graphHorizontalLines#
cpuUsageColor=#green#
cpuTempColor=#red#
cpuGradientAngle=180
cpuGradientColor1=#lightBackgroundColor#,255
cpuGradientColor2=#lightBackgroundColor#,0
;GradientOverlay=#cpuGradientAngle# | #cpuGradientColor1# ; 0.0 | #cpuGradientColor1# ; 0.25 | #cpuGradientColor2# ; 1.0

; Color Scheme - Media Player
mediaPlayerFont=#font#
mediaPlayerFontColor=#fontColor#
mediaPlayerFontHighlightColor=#fontHighlightColor#
mediaPlayerIconColor=#teal#
mediaPlayerIconHighlightColor=#white#
mediaPlayerBackgroundColor=#lightBackgroundColor#

; Color Scheme - Network
netFont=#font#
netFontColor=#fontColor#
netFontHighlightColor=#fontHighlightColor#
netBackgroundColor=#lightBackgroundColor#
netGraphHorizontalLines=#graphHorizontalLines#
netOutColor=#red#
netInColor=#green#
netGradientAngle=180
netGradientColor1=#lightBackgroundColor#,255
netGradientColor2=#lightBackgroundColor#,0
;GradientOverlay=#netGradientAngle# | #netGradientColor1# ; 0.0 | #netGradientColor1# ; 0.25 | #netGradientColor2# ; 1.0

; Color Scheme - ShortcutBar
scbIconColor=#teal#
scbIconHighlightColor=#white#
scbBackgroundColor=#lightBackgroundColor#

; Color Scheme - ShortcutPanel
scpFont=#font#
scpFontColor=#fontColor#
scpFontHighlightColor=#fontHighlightColor#
scpIconColor=#teal#
scpIconHighlightColor=#white#
scpBackgroundColor=#lightBackgroundColor#

; Color Scheme - SystemInfo
sysInfoFont=#font#
sysInfoFontColor=#fontColor#
sysInfoFontHighlightColor=#fontHighlightColor#
sysInfoIconColor=#teal#
sysInfoIconHighlightColor=#white#
sysInfoBackgroundColor=#lightBackgroundColor#
sysInfoUserIconColor=#teal#
sysInfoHostIconColor=#blurple#
sysInfoUptimeIconColor=#purple#
sysInfoAudioIconColor=#red#

; Color Scheme - SystemUsage
sysUsageFont=#font#
sysUsageFontColor=#fontColor#
sysUsageFontHighlightColor=#fontHighlightColor#
sysUsageLineColor=#white#
sysUsageCPUColor=#orange#
sysUsageRAMColor=#blue#
sysUsageBackgroundColor=#lightBackgroundColor#

; Color Scheme - SystemUsageDrives
sysUsageDriveFont=#font#
sysUsageDriveFontColor=#fontColor#
sysUsageDriveLineColor=#white#
sysUsageDriveAColor=#teal#
sysUsageDriveBColor=#pink#
sysUsageDriveBackgroundColor=#lightBackgroundColor#

; Color Scheme - WeatherDefault
weatherFont=#GoogleSans#
weatherFontColor=#white#
weatherGradientAngle=45
weatherGradientColor1=#lightBlue#
weatherGradientColor2=#skyBlue#
;WeatherGradient=#weatherGradientAngle# | #weatherGradientColor1# ; 0.0 | #weatherGradientColor2# ; 1.0

; Color Scheme - WeatherGoogle
googleFont=#GoogleSans#
googleFontColor=#white#
googleGradientAngle=45
googleGradientColor1=#googleBlue#
googleGradientColor2=#googleRed#
;WeatherGoogleGradient=#googleGradientAngle# | #googleGradientColor1# ; 0.0 | #googleGradientColor2# ; 1.0

; Color Scheme - WeatherGreeting
greetingBackgroundColor=#red#

; Icons
IconClose=#@#\Images\Icons\close.png
; Icons - CPU:
IconCPU=#@#\Images\Icons\cpu.png
; Icons - MediaPlayer:
IconMusic=#@#\Images\Icons\music.png
IconPlay=#@#\Images\Icons\play.png
IconPause=#@#\Images\Icons\pause.png
IconPrev=#@#\Images\Icons\previous.png
IconNext=#@#\Images\Icons\next.png
; Icons - Network:
IconNetwork=#@#\Images\Icons\network.png
IconDownload=#@#\Images\Icons\download.png
IconUpload=#@#\Images\Icons\upload.png
; Icons - SystemInfo:
IconUser=#@#\Images\Icons\user.png
IconHost=#@#\Images\Icons\host.png
IconAudio=#@#\Images\Icons\audio.png
; Icons - WeatherGreeting:
IconHeart=#@#\Images\Icons\heart.png