[Variables]
; Media Player
Player=Spotify
MediaPlayerPath="C:\Users\lorde\AppData\Roaming\Spotify\Spotify.exe"
MediaPlayerParameters=""
EnableAutoHide=1

; Network
NetworkUploadMbps=198.53
NetworkDownloadMbps=313.42
NetworkAverageSize=1

; Weather - Weatherbit.io:
weatherCity=Letterkenny
weatherCountry=IE
weatherAPIKey=

; WeatherGreeting: Time of Day Response
TimeOfDay="00":"Good Night","01":"Good Night","02":"Good Night","03":"Good Night","04":"Good Night","05":"Good Night","06":"Good Night","07":"Good Morning","08":"Good Morning","09":"Good Morning","10":"Good Morning","11":"Good Morning","12":"Good Afternoon","13":"Good Afternoon","14":"Good Afternoon","15":"Good Afternoon","16":"Good Afternoon","17":"Good Afternoon","18":"Good Evening","19":"Good Evening","20":"Good Evening","21":"Good Evening","22":"Good Evening","23":"Good Evening"

;https://api.weatherbit.io/v2.0/current?city=Letterkenny&country=IE&key=***REMOVED***
