[MeasureState]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=State
Substitute="0":"#IconPlay#","1":"#IconPause#","2":"#IconPlay#"
UpdateDivider=2

[MeasureCover]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=Cover
UpdateDivider=100

[MeasureTrack]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=Title
UpdateDivider=100

[MeasureArtist]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#Player#
PlayerType=Artist
UpdateDivider=100