[MeasureState]
Measure=Plugin
Plugin=WebNowPlaying.dll
PlayerType=State
Substitute="0":"#IconPlay#","1":"#IconPause#","2":"#IconPlay#"
UpdateDivider=2

[MeasureCover]
Measure=Plugin
Plugin=WebNowPlaying.dll
PlayerType=Cover

[MeasureTrack]
Measure=Plugin
Plugin=WebNowPlaying.dll
PlayerType=Title
UpdateDivider=100

[MeasureArtist]
Measure=Plugin
Plugin=WebNowPlaying.dll
PlayerType=Artist
UpdateDivider=100

[MeasurePosition]
Measure=Plugin
Plugin=WebNowPlaying.dll
PlayerType=Position
UpdateDivider=20

[MeasureDuration]
Measure=Plugin
Plugin=WebNowPlaying.dll
PlayerType=Duration
UpdateDivider=20

[MeasureProgress]
Measure=Plugin
Plugin=WebNowPlaying.dll
PlayerType=Progress
UpdateDivider=20