; You will need to edit ShortcutBar.ini as well,
; to uncomment relevant IF conditions in [MeasureSkinCountTest]
; and the corresponding [MeterSkin*] Meter.

[Variables]
SkinCount=3
SkinIconSize=25
SkinTotalWidth=400
SkinWidthPadding=25

; Skin 1
Skin1=Internet
Skin1Icon=#@#\Images\Icons\internet.png
Skin1Path="Conky Gemini\ShortcutPanel"
Skin1File=ShortcutInternet.ini

; Skin 2
Skin2=Games
Skin2Icon=#@#\Images\Icons\game.png
Skin2Path="Conky Gemini\ShortcutPanel"
Skin2File=ShortcutGames.ini

; Skin 3
Skin3=Apps
Skin3Icon=#@#\Images\Icons\user.png
Skin3Path="Conky Gemini\ShortcutPanel"
Skin3File=ShortcutApps.ini

; Skin 4
Skin4=
Skin4Icon=#@#\Images\Icons\user.png
Skin4Path=
Skin4File=

; Skin 5
Skin5=
Skin5Icon=#@#\Images\Icons\user.png
Skin5Path=
Skin5File=
