[Variables]
App1="PIA VPN"
App1Icon="#@#\Images\Icons\pia.png"
App1Overlay="#@#\Images\Overlays\pia.png"
App1Path="C:\Program Files\Private Internet Access\pia-client.exe"
App1Parameters=""

App2=Deluge
App2Icon="#@#\Images\Icons\deluge.png"
App2Overlay="#@#\Images\Overlays\deluge.png"
App2Path="C:\Program Files\Deluge\deluge.exe"
App2Parameters=""

App3=Jackett
App3Icon="#@#\Images\Icons\jackett.png"
App3Overlay="#@#\Images\Overlays\jackett.png"
App3Path="C:\ProgramData\Jackett\JackettTray.exe"
App3Parameters=""

App4=Sonarr
App4Icon="#@#\Images\Icons\sonarr.png"
App4Overlay="#@#\Images\Overlays\sonarr.png"
App4Path="C:\ProgramData\Sonarr\bin\Sonarr.exe"
App4Parameters="/icon"

App5=Radarr
App5Icon="#@#\Images\Icons\radarr.png"
App5Overlay="#@#\Images\Overlays\radarr.png"
App5Path="C:\ProgramData\Radarr\bin\Radarr.exe"
App5Parameters="/icon"

App6=Lidarr
App6Icon="#@#\Images\Icons\lidarr.png"
App6Overlay="#@#\Images\Overlays\lidarr.png"
App6Path="C:\ProgramData\Lidarr\bin\Lidarr.exe"
App6Parameters="/icon"

App7="Plex Server"
App7Icon="#@#\Images\Icons\plex.png"
App7Overlay="#@#\Images\Overlays\plex.png"
App7Path="C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe"
App7Parameters=

App8=
App8Icon=
App8Overlay=
App8Path=
App8Parameters=