[Variables]
App1=Spotify
App1Icon="#@#\Images\Icons\spotify.png"
App1Overlay="#@#\Images\Overlays\spotify.png"
;App1Path="shell:appsFolder\SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify"
App1Path="C:\Users\lorde\AppData\Roaming\Spotify\Spotify.exe"
App1Parameters=""

App2=Hue Sync
App2Icon="#@#\Images\Icons\huesync.png"
App2Overlay="#@#\Images\Overlays\huesync.png"
App2Path="C:\Program Files\Hue Sync\HueSync.exe"
App2Parameters=

App3=ScreenBlank
App3Icon="#@#\Images\Icons\screenblank.png"
App3Overlay="#@#\Images\Overlays\screenblank.png"
App3Path="D:\Softwares\MultiscreenBlank2\MultiscreenBlank2.exe"
App3Parameters=

App4=
App4Icon=
App4Overlay=
App4Path=
App4Parameters=

App5=
App5Icon=
App5Overlay=
App5Path=
App5Parameters=""

App6=
App6Icon=
App6Overlay=
App6Path=
App6Parameters=

App7=
App7Icon=
App7Overlay=
App7Path=
App7Parameters=

App8=
App8Icon=
App8Overlay=
App8Path=
App8Parameters=