[Variables]
App1=Discord
App1Icon="#@#\Images\Icons\discord.png"
App1Overlay="#@#\Images\Overlays\discord.png"
App1Path="C:\Users\lorde\AppData\Local\Discord\Update.exe"
App1Parameters="--processStart Discord.exe"

App2=Steam
App2Icon="#@#\Images\Icons\steam.png"
App2Overlay="#@#\Images\Overlays\steam.png"
App2Path="C:\Program Files (x86)\Steam\steam.exe"
App2Parameters=""

App3=GOG
App3Icon="#@#\Images\Icons\gog.png"
App3Overlay="#@#\Images\Overlays\gog.png"
App3Path="C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe"
App3Parameters=""

App4=Epic Games
App4Icon="#@#\Images\Icons\epic.png"
App4Overlay="#@#\Images\Overlays\epic.png"
App4Path="C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe"
App4Parameters=""

App5=DS4Windows
App5Icon="#@#\Images\Icons\game.png"
App5Overlay="#@#\Images\Overlays\ds4windows.png"
App5Path="C:\Program Files\DS4Windows\DS4Windows.exe"
App5Parameters=""

App6=Xbox
App6Icon="#@#\Images\Icons\xbox.png"
App6Overlay="#@#\Images\Overlays\xbox.png"
;App6Path="shell:appsFolder\Microsoft.GamingApp_8wekyb3d8bbwe!Microsoft.Xbox.App"
App6Path="shell:appsFolder\Microsoft.GamingApp_8wekyb3d8bbwe!App"
App6Parameters=""

App7=Origin
App7Icon="#@#\Images\Icons\origin.png"
App7Overlay="#@#\Images\Overlays\origin.png"
App7Path="C:\Program Files (x86)\Origin\Origin.exe"
App7Parameters=""

App8=UPlay
App8Icon="#@#\Images\Icons\uplay.png"
App8Overlay="#@#\Images\Overlays\uplay.png"
App8Path="C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\Uplay.exe"
App8Parameters=""
